dist: xenial
language: csharp
mono: none
dotnet: 2.2
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
  # NUGET_API_KEY
  - secure: yRO6MECm8MyZV/taDrjE8vzgceNdYNFM0Oqhje6+ZLUKJOt1okqWTXH09i74DoxtTRqNshSqekRrviN62/JdMV3LOKKl48j8idLxR3Kd0lPkcxYsno1vhpAwtypc3HQZLJ9H5vfKZdYToHOu0QZT0g5chiFjO5yradKZA0zWrSj7Gen03+40Ok55vXM636QnhQuJt7YRuiox1GwM2SxX+RXqNFCPbxqPpzwsspvvmk/fYVGagrIuxzXiXqNHXb1BEuknpOwcCsvfBlzfeGCNFLtoWJurkYlRSYBWZNaJXe/0xsNdIWZRcEiiNP9oy7gl7uwjyuTOLQ2Z3JGMGdRSCfYEpiAUKUJjDNlKSLaEe5aXcHDvg9g+R25YZqLqKGg2Kys9l/51m5zoKJBN7vhCymZ0pF12xiWUdIhg+2NP8uQhQ9aO9Om1PydnNtXpsnSCHaTnHgY9cVIX8E1Hwb0k+vyaR/15CRsHd0sm+2ydBU9ibvD1/b+TGckWmwyGKG4cwmuDRsZDJQUktMFkUWFeoVAtF5l4AV5A3YXo60DgXPHdMzCMUxSBR/nVo3baOIRFfHubm4V2r+/FGCPWwXI4YkkUte7w9bP/bXvGAe7qQcd2eD/Fl5Ax3EZE15msksO0p3OlhkLAPVgq8xuIEx1Tzn4epBOzlENAhIahS0QkIas=
install:
- dotnet restore src/Shawarma.AspNetCore.sln
script:
- dotnet build -c Release /p:Version=${TRAVIS_TAG:-1.0.0} src/Shawarma.AspNetCore.sln
- dotnet test --no-build -c Release src/Shawarma.UnitTests/Shawarma.UnitTests.csproj
- dotnet pack --no-build -c Release /p:Version=${TRAVIS_TAG:-1.0.0} src/Shawarma.AspNetCore.sln
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push -s https://api.nuget.org/v3/index.json -k "${NUGET_API_KEY}" **/*.${TRAVIS_TAG}.nupkg
  on:
    tags: true
